livery = {

	{"f18c1", 0 ,"F18C_1_DIFF",false};
	{"f18c1", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};

	
	{"f18c2", 0 ,"F18C_2_DIFF",false};
	{"f18c2", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};

	
	{"F18C_BORT_NUMBER_NOSE_L_100", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_L_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_NOSE_L_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_10", DECAL ,"empty",true};

	{"F18C_BORT_NUMBER_NOSE_L_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_L_01", DECAL ,"empty",true};
	

	{"F18C_BORT_NUMBER_NOSE_R_100", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_R_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_NOSE_R_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_10", DECAL ,"empty",true};

	{"F18C_BORT_NUMBER_NOSE_R_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_R_01", DECAL ,"empty",true};
	
	
	

	
	{"F18C_BORT_NUMBER_ZAK_L_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_ZAK_L_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_ZAK_L_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_L_01", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_ZAK_R_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_ZAK_R_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_ZAK_R_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_ZAK_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_ZAK_R_01", DECAL ,"empty",true};

	
	
	{"F18C_BORT_NUMBER_KIL_L_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_L_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_L_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_L_01", DECAL ,"empty",true};	
	
	{"F18C_BORT_NUMBER_KIL_R_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_R_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_R_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_R_01", DECAL ,"empty",true};		

	
	
	
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_L_01", DECAL ,"empty",true};
	

	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_kuw_R_01", DECAL ,"empty",true};		
	


	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_R_01", DECAL ,"empty",true};	
	
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Kuw_L_01", DECAL ,"empty",true};		



	
	

	
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_NOSE_fin_L_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_fin_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_L_01", DECAL ,"empty",true};
	
	
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_NOSE_fin_R_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_NOSE_fin_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_NOSE_fin_R_01", DECAL ,"empty",true};			
	
	

	
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_Switz_R_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_R_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_R_01", DECAL ,"empty",true};	
	
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_100", DECAL ,"empty",true};
	
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_KIL_Switz_L_01", 0 ,"F18C_2_DIFF",false};
	{"F18C_BORT_NUMBER_KIL_Switz_L_01", ROUGHNESS_METALLIC ,"F18C_2_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_KIL_Switz_L_01", DECAL ,"empty",true};

	
	
	
	{"F18C_BORT_NUMBER_STV_aus_R_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_STV_aus_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_STV_aus_R_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_STV_aus_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_R_01", DECAL ,"empty",true};	
	

	
	{"F18C_BORT_NUMBER_STV_aus_L_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_STV_aus_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_STV_aus_L_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_STV_aus_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_STV_aus_L_01", DECAL ,"empty",true};		
		

	{"F18C_BORT_NUMBER_MTW_aus_R_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_MTW_aus_R_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_R_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_MTW_aus_R_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_MTW_aus_R_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_R_01", DECAL ,"empty",true};	


	{"F18C_BORT_NUMBER_MTW_aus_L_10", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_MTW_aus_L_10", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_L_10", DECAL ,"empty",true};	

	{"F18C_BORT_NUMBER_MTW_aus_L_01", 0 ,"F18C_1_DIFF",false};
	{"F18C_BORT_NUMBER_MTW_aus_L_01", ROUGHNESS_METALLIC ,"F18C_1_DIF_RoughMet",true};
	{"F18C_BORT_NUMBER_MTW_aus_L_01", DECAL ,"empty",true};

--Fuel Tanks
	{"FPU_8A", 0 ,"FPU_8A",false};
	{"FPU_8A", 2 ,"FPU_8A_Diff_RoughMet",true};

}
name = "(v)USMC VMFA-115 'Silver Eagles' CO VE-201"
countries = {"USA",}
--Property of Digital Coalition Airforce Skinpack
--By DCAF CTCVisuals 01/07/2019
--https://www.fiverr.com/ctcvisuals/create-custom-dcs-world-liveries